package com.onze.api.match;

public enum LiveMatchChangeType {
    MATCH_STARTED,
    SCORE_UPDATED,
    TEAM_IMAGE_UPDATED,
    GOAL_ADDED,
    CARD_ADDED,
    GOAL_REMOVED,
    CARD_REMOVED,
    PERIOD_ADDED_TIME_UPDATED,
    PERIOD_FINISHED,
    PERIOD_STARTED,
    PENALTY_SHOOTOUT_READY,
    PENALTY_SHOOTOUT_STARTED,
    PENALTY_ATTEMPT_RECORDED,
    PENALTY_SHOOTOUT_DECIDED,
    MATCH_FINISHED,
    MATCH_RESET
}
