package com.onze.api.match;

public enum MatchNotificationType {
    MATCH_CREATED,
    ATTENDANCE_OPENED,
    ATTENDANCE_REMINDER,
    PAYMENT_REMINDER,
    PAYMENT_REPORTED,
    PAYMENT_CONFIRMED,
    MATCH_TOMORROW,
    TEAM_FULL,
    MATCH_CANCELLED,
    SERIES_CANCELLED
}
