package com.onze.api.match;

public enum MatchNotificationType {
    MATCH_CREATED,
    ATTENDANCE_OPENED,
    ATTENDANCE_REMINDER,
    PAYMENT_REMINDER,
    PAYMENT_DEADLINE_REMOVAL,
    PAYMENT_REPORTED,
    PAYMENT_CONFIRMED,
    PAYMENT_SETTLEMENT_REQUIRED,
    PAYMENT_SETTLEMENT_RESOLVED,
    CREDIT_APPLIED,
    REPLACEMENT_ADDED,
    REPLACEMENT_FILLED,
    MATCH_TOMORROW,
    TEAM_FULL,
    MATCH_CANCELLED,
    SERIES_CANCELLED,
    LIVE_MATCH_STARTED,
    LIVE_MATCH_GOAL,
    LIVE_MATCH_YELLOW_CARD,
    LIVE_MATCH_SECOND_YELLOW_CARD,
    LIVE_MATCH_RED_CARD,
    LIVE_MATCH_FINISHED
}
