package com.onze.api.technical;

public enum PlayerSkill {
    PASSING,
    LONG_PASSING,
    CROSSING,
    BALL_CONTROL,
    DRIBBLING,
    FINISHING,
    SPEED,
    AGILITY,
    STRENGTH,
    HEADING,
    TACKLING,
    DEFENSIVE_POSITIONING,
    ATTACKING_POSITIONING,
    VISION,
    GOALKEEPER_REFLEXES,
    GOALKEEPER_POSITIONING,
    GOALKEEPER_RUSHING_OUT
}
