name: Docker CI

on:
  push:
    branches:
      - development
      - feature/**
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build production image
        run: docker build -t onze-api:ci .
